<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ArcanistCSharpASTLinter' => 'arcanist/lint/linter/ArcanistCSharpASTLinter.php',
    'ArcanistCSharpASTLinterTestCase' => 'arcanist/lint/linter/__tests__/ArcanistCSharpASTLinterTestCase.php',
    'BracePlacementCSharpLintPolicy' => 'arcanist/lint/linter/csharp/BracePlacementCSharpLintPolicy.php',
    'CSharpLintPolicy' => 'arcanist/lint/linter/csharp/CSharpLintPolicy.php',
    'IndentationLintPolicy' => 'arcanist/lint/linter/csharp/IndentationLintPolicy.php',
    'WhitespaceBeforeAfterParenthesisLintPolicy' => 'arcanist/lint/linter/csharp/WhitespaceBeforeAfterParenthesisLintPolicy.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ArcanistCSharpASTLinter' => 'ArcanistLinter',
    'ArcanistCSharpASTLinterTestCase' => 'ArcanistLinterTestCase',
    'BracePlacementCSharpLintPolicy' => 'CSharpLintPolicy',
    'CSharpLintPolicy' => 'Phobject',
    'IndentationLintPolicy' => 'CSharpLintPolicy',
    'WhitespaceBeforeAfterParenthesisLintPolicy' => 'CSharpLintPolicy',
  ),
));
